### ISSUE TITLE
vlsm todo

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [BrunoTeixeira1996/network-scripts#1]
- [x] if network not /24 then `network['network_first_host'] = 1` its wrong (getFirstNetwork())
- [x] found a bug in sumStringInt() , when doing .129 + 1 the result is 1291 but should be 130
- [ ] when broadcast == .255 , increase the third octect by 1

**Comment by BrunoTeixeira1996** [comment]
bug when using 192.168.10.0 ...
